version: '3'

services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2404
      - POSTGRES_DB=pastbinDB